name: Heroku Awake

on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://custombucks-api.herokuapp.com/"
